import GlobalState from "@/context";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import { Provider as jotaiProvider } from "jotai";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalState>
          <jotaiProvider>
            <Navbar />
            <main className="flex min-h-screen flex-col mt-[80px]">
              {children}
            </main>
          </jotaiProvider>
        </GlobalState>
      </body>
    </html>
  );
}
